mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one
    username: root
    password: 5455584

server:
  port: 80





